website/music/urls.py
from django.conf.urls import url
from . import views
app_name='music'

urlpatterns = [
	#/music/
    url(r'^$',views.IndexView.as_view(),name='index'),
    #/music/71/
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail' ),
    url(r'album/add/$', views.AlbumCreate.as_view(),name='album-add'),

    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(),name='album-update'),

    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(),name='album-delete'),
    
   

]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^music/',include('music.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
	artist= models.CharField(max_length=250)
	album_title=models.CharField(max_length=500)
	genre=models.CharField(max_length=100)
	album_logo=models.CharField(max_length=2000)

	def get_absolute_url(self):
		return reverse('music:detail',kwargs={'pk':self.pk})

	def __str__(self):
		return self.album_title +' - '+self.artist


class Song(models.Model):
	album=models.ForeignKey(Album, on_delete=models.CASCADE)#Foreignkey is used to link this to Albums.
	file_type=models.FileField()
	song_title=models.CharField(max_length=500)
	is_favourite=models.BooleanField(default=False)

	

	def __str__(self):
		return self.song_title

website/music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView,DeleteView
from .models import Album,Song
from django.core.urlresolvers import reverse_lazy

class IndexView(generic.ListView):

	template_name='music/index.html'
	context_object_name='all_albums'

	def get_queryset(self):
		return Album.objects.all()
class DetailView(generic.DetailView):
	model=Album
	template_name='music/detail.html'
class AlbumCreate(CreateView):
	model=Album
	fields=['artist','album_title','genre','album_logo']
class AlbumUpdate(UpdateView):
	model=Album
	fields=['artist','album_title','genre','album_logo']
class AlbumDelete(DeleteView):
	model=Album
	success_url=reverse_lazy('music:index')

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% include 'music/form-template.html' %}

<button type="submit" class="btn btn-success">Submit</button>	

</form>

{% endblock %}
</body>
</html>

website/music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Musique{% endblock %}</title>
	{% load staticfiles %}
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Satisfy" />
	<link href="https://fonts.googleapis.com/css?family=Ubuntu+Condensed" rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/d3js/5.7.0/d3.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

	
</head>
<body>
<nav class="navbar navbar-inverse bg-dark navbar-dark"> 
<div class="container-fluid">
	<!-- logo -->
	<div class="navbar-header">
		
		<a class="navbar-brand" href="{% url 'music:index' %}"> <strong><i class="fas fa-guitar">&nbsp;</i>Musique</strong> </a>
	</div>

		<ul class="nav navbar-nav navbar-left">
			<li class="active">
				<a class="navbar-brand" href="{% url 'music:index' %}">
					<i class="fas fa-compact-disc"></i>&nbsp;
					Albums
				</a>
			</li>
			</ul>
			<ul class="nav navbar-nav navbar-left">
			<li >
				<a class="navbar-brand" href="#">
					
					
				</a>
			</li>
			
		</ul>
		<form class="navbar-form navbar-left" role="search" method="get" action="#"> 
		<div class="form-group">
			<input type="text" class="form-control" name="q" value="">
		</div>
		<button type="submit" class="btn btn-default ">Search</button>
		</form>
			<ul class="nav navbar-nav navbar-right">
						<li class="active">
							<a class="navbar-brand" href="{% url 'music:album-add' %}">
								<i class="fas fa-plus"></i>&nbsp;
								Add Albums
							</a>
						</li>
						</ul>

		<ul class="nav navbar-nav navbar-right">
						<li class="active">
							<a class="navbar-brand" href="http://127.0.0.1:8000/admin/music/song/">
								<i class="fas fa-music"></i>&nbsp;
								
								Add Songs
							</a>
						</li>
						</ul>				
		<ul class="nav navbar-nav navbar-left">
			<li class="active">
				<a class="navbar-brand" href="http://127.0.0.1:8000/admin/">
					<i class="fas fa-sign-in-alt"></i>&nbsp;
					Log in
				</a>
			</li>
			</ul>
			 
</div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{{ album.album_title }}{% endblock %}</title>

</head>
<body>

	{% block body %}	
<img src="{{ album.album_logo }}" height="200" width="200">
<h2><strong>{{ album.artist }}</strong></h2>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'music:album-update' album.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="album_id" value="{{ album.id }}">
    <button type="submit" class="btn btn-primary" ><i class="fas fa-edit"></i> Edit Album Details</button>
</form>
<form action="{% url 'music:album-delete' album.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="album_id" value="{{ album.id }}">
    <button type="submit" class="btn btn-danger" ><i class="fas fa-trash-alt"></i> Delete Album</button>
</form>

 <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
<td>{{ song.song_title }}</td>
<td><audio controls src="{{ song.file_type.url }}">
<div style="border: 1px solid black ; padding: 8px ;">
Sorry, your browser does not support the <audio> tag used in this demo.
</div>
</audio></td>


	{% endfor %}

	
	


{% endblock %}
</body>
</html>

website/music/templates/music/form-template.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for field in form %}
<div class="form-group">
	<div><span class="text-danger small">{{field.errors}}</span></div>
<label class="control_label">{{field.label_tag}}</label>
<div>{{field}}</div>
</div>
{%endfor%}
</body>
</html>

website/music/templates/music/index.html
{% extends 'music/base.html' %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	

</head>
<body>

	

	{% block body %}
	{% if all_albums %}
    
	<ul >
		<h3>Here are all the albums: </h3>
		{% for album in all_albums %}
         <div>
		<li class="horizontal"><a href="{% url 'music:detail' album.id %}"><img src="{{ album.album_logo }}" class="img-responsive"></a>
             <div class="caption">
                            <a href="{% url 'music:detail' album.id %}"><h2>{{ album.album_title }}</h2></a>
<h4>{{ album.artist }}</h4>

        </li>	
		</div><br>
        {% endfor %}
	</ul>
	{% else %}
	<h3>You don't have any albums.</h3>
	{% endif %}
	{% endblock %}
</body>
</html>>

website/music/templates/music/song-template.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% for field in form %}
<div class="form-group">
	<div><span class="text-danger small">{{field.errors}}</span></div>
<label class="control_label">{{field.label_tag}}</label>
<div>{{field}}</div>
</div>
{%endfor%}
</body>
</html>

website/music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new album{% endblock %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{% block body %}
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% include 'music/song-template.html' %}

<button type="submit" class="btn btn-success">Submit</button>	

</form>

{% endblock %}
</body>
</html>